Rocnikovka warning
mensagymnazium/IntranetGen3 pull request #154
Opened 2024-04-23 14:07 UTC by JStrm

2024-04-24 09:30 UTC, Xopabyteh requested changes
Works on my machine, odeberte to TODO a ja dam merge

2024-04-24 09:30 UTC, Xopabyteh commented on Web.Client/Pages/Electives/SubjectList.razor.cs
Funguje, zkusil jsem, odebrat todo

2024-04-24 09:31 UTC, Xopabyteh commented on Web.Client/Pages/Electives/SubjectList.razor.cs
cc @JStrm

2024-04-30 11:17 UTC, hakenr approved these changes
lgtm

2024-04-30 11:18 UTC, merged